CREATE DATABASE funnel_analysis;
USE funnel_analysis;

SHOW TABLES;

SELECT * FROM funnel_clean_data LIMIT 12;

#Q1. How many customers came from each acquisition channel?

SELECT acquisition_channel, COUNT(*) AS total_customers
FROM funnel_clean_data
GROUP BY acquisition_channel
ORDER BY total_customers DESC;

#Q2. What is the average Customer Acquisition Cost (CAC) per channel?

SELECT acquisition_channel, ROUND(AVG(marketing_spend_per_user), 2) AS avg_CAC
FROM funnel_clean_data
GROUP BY acquisition_channel
ORDER BY avg_CAC ASC;

#Q3. What is the average Lifetime Value (LTV) per channel?

SELECT acquisition_channel, ROUND(AVG(lifetime_value), 2) AS avg_LTV
FROM funnel_clean_data
GROUP BY acquisition_channel
ORDER BY avg_LTV DESC;

#Q4. Which channel gives the best return — LTV vs CAC ratio?

SELECT acquisition_channel,
ROUND(AVG(lifetime_value), 2) AS avg_LTV,
ROUND(AVG(marketing_spend_per_user), 2) AS avg_CAC,
ROUND(AVG(lifetime_value) / AVG(marketing_spend_per_user), 2) AS LTV_CAC_ratio
FROM funnel_clean_data
GROUP BY acquisition_channel
ORDER BY LTV_CAC_ratio DESC;

#Q5. What is the overall churn rate?

SELECT COUNT(*) AS total_customers, SUM(churn) AS churned_customers,
ROUND(SUM(churn) * 100.0 / COUNT(*), 2) AS churn_rate_pct,
ROUND((1 - SUM(churn) * 1.0 / COUNT(*)) * 100, 2) AS retention_rate_pct
FROM funnel_clean_data;

#Q6. What is the churn rate broken down by each acquisition channel?

SELECT acquisition_channel, COUNT(*) AS total_customers,
SUM(churn) AS churned,
ROUND(SUM(churn) * 100.0 / COUNT(*), 2) AS churn_rate_pct
FROM funnel_clean_data
GROUP BY acquisition_channel
ORDER BY churn_rate_pct DESC;

#Q7. Does customer satisfaction score directly impact churn rate?

SELECT satisfaction_score, COUNT(*) AS total_customers, SUM(churn) AS churned,
ROUND(SUM(churn) * 100.0 / COUNT(*), 2) AS churn_rate_pct
FROM funnel_clean_data
GROUP BY satisfaction_score
ORDER BY satisfaction_score ASC;

#Q8. Do customers who raise more support tickets tend to churn more?

SELECT support_tickets, COUNT(*) AS total_customers, SUM(churn) AS churned,
ROUND(SUM(churn) * 100.0 / COUNT(*), 2) AS churn_rate_pct
FROM funnel_clean_data
GROUP BY support_tickets
ORDER BY support_tickets ASC;

#Q9. What is the total and average revenue generated by each acquisition channel?

SELECT acquisition_channel, COUNT(*) AS total_customers,
ROUND(SUM(total_spent), 2) AS total_revenue,
ROUND(AVG(total_spent), 2) AS avg_revenue_per_customer
FROM funnel_clean_data
GROUP BY acquisition_channel
ORDER BY total_revenue DESC;

#Q10. Who spends more — Premium users or Regular users?

SELECT is_premium_user, COUNT(*) AS total_customers,
ROUND(AVG(total_spent), 2) AS avg_spent,
ROUND(AVG(lifetime_value), 2) AS avg_LTV,
ROUND(SUM(churn) * 100.0 / COUNT(*), 2) AS churn_rate_pct
FROM funnel_clean_data
GROUP BY is_premium_user;

#Q11. Which subscription type generates more revenue — Annual or Monthly?

SELECT subscription_type, COUNT(*) AS total_customers,
ROUND(AVG(total_spent), 2) AS avg_spent,
ROUND(AVG(lifetime_value), 2) AS avg_LTV,
ROUND(SUM(churn) * 100.0 / COUNT(*), 2) AS churn_rate_pct
FROM funnel_clean_data
GROUP BY subscription_type
ORDER BY avg_LTV DESC;

#Q12. Do customers who used discounts have higher or lower lifetime value?

SELECT discount_used, COUNT(*) AS total_customers,
ROUND(AVG(total_spent), 2) AS avg_spent,
ROUND(AVG(lifetime_value), 2) AS avg_LTV,
ROUND(SUM(churn) * 100.0 / COUNT(*), 2) AS churn_rate_pct
FROM funnel_clean_data
GROUP BY discount_used;

#Q13. Which acquisition channel drives the highest average engagement score?

SELECT acquisition_channel,
ROUND(AVG(engagement_score), 2) AS avg_engagement_score,
ROUND(AVG(total_visits), 1) AS avg_visits,
ROUND(AVG(avg_session_time), 1) AS avg_session_mins,
ROUND(AVG(email_open_rate), 2) AS avg_email_open_rate
FROM funnel_clean_data
GROUP BY acquisition_channel
ORDER BY avg_engagement_score DESC;

#Q14. Do customers who visit more tend to spend more?

SELECT 
    CASE 
        WHEN total_visits < 20 THEN 'Low (0-20)'
        WHEN total_visits BETWEEN 20 AND 50 THEN 'Medium (20-50)'
        WHEN total_visits BETWEEN 50 AND 100 THEN 'High (50-100)'
        ELSE 'Very High (100+)'
    END AS visit_segment,
    COUNT(*) AS total_customers,
    ROUND(AVG(total_spent), 2) AS avg_spent,
    ROUND(AVG(lifetime_value), 2) AS avg_LTV
FROM funnel_clean_data
GROUP BY visit_segment
ORDER BY avg_spent DESC;

#Q15. Which device type generates the highest revenue per visit?

SELECT device_type, COUNT(*) AS total_customers,
ROUND(AVG(revenue_per_visit), 2) AS avg_revenue_per_visit,
ROUND(AVG(total_spent), 2) AS avg_total_spent,
ROUND(AVG(engagement_score), 2) AS avg_engagement
FROM funnel_clean_data
GROUP BY device_type
ORDER BY avg_revenue_per_visit DESC;